# Custom Language File for Launcher Customizer

[ejs.app]
title = "Mangos Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/imperio-mango"

[ejs.settings]
sourceGithubLink = "https://github.com/Clyzer/MangoLauncher"
supportLink = "https://github.com/Clyzer/MangoLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENIDO A IMPERIO MANGO"
welcomeDescription = "Nuestro servidor intenta ofrecer la mejor experiencia de juego posible. ¡Únete a nosotros y disfruta de la experiencia de juego de Minecraft!"
welcomeDescCTA = "¡Únete a nosotros!"
